src/Entity/OrderItem.php
<?php

namespace App\Entity;

use App\Repository\OrderItemRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=OrderItemRepository::class)
 */
class OrderItem
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Product::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $product;

    /**
     * @ORM\Column(type="integer")
     * @Assert\NotBlank()
     * @Assert\GreaterThanOrEqual(1)
     */
    private $quantity;

    /**
     * @ORM\ManyToOne(targetEntity=Order::class, inversedBy="items")
     * @ORM\JoinColumn(nullable=false)
     */
    private $orderRef;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getProduct(): ?Product
    {
        return $this->product;
    }

    public function setProduct(?Product $product): self
    {
        $this->product = $product;

        return $this;
    }

    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    public function setQuantity(int $quantity): self
    {
        $this->quantity = $quantity;

        return $this;
    }

    public function getOrderRef(): ?Order
    {
        return $this->orderRef;
    }

    public function setOrderRef(?Order $orderRef): self
    {
        $this->orderRef = $orderRef;

        return $this;
    }


    /**
     * Tests if the given item given corresponds to the same order item.
     *
     * @param OrderItem $item
     *
     * @return bool
     */
    public function equals(OrderItem $item): bool {
        return $this->getProduct()->getId() === $item->getProduct()->getId();
    }

    public function getTotal(): float
    {
        return $this->getProduct()->getPrice() * $this->getQuantity();
    }
}

src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ProductRepository::class)
 */
class Product
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $Name;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $price;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $quantity;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Image;

    /**
     * @ORM\ManyToOne(targetEntity=Category::class, inversedBy="products")
     */
    private $category;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(?float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    public function setQuantity(?int $quantity): self
    {
        $this->quantity = $quantity;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getImage()
    {
        return $this->Image;
    }

    public function setImage( $Image)
    {
        if ($Image != null) {
            $this->Image = $Image;
        }

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }
}

src/Form/CartType.php
<?php

namespace App\Form;

use App\Entity\Order;
use App\Form\EventListener\ClearCartListener;
use App\Form\EventListener\RemoveCartItemListener;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CartType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('items', CollectionType::class, [
                'entry_type' => CartItemType::class
            ])
            ->add('clear', SubmitType::class);

        $builder->addEventSubscriber(new RemoveCartItemListener());
        $builder->addEventSubscriber(new ClearCartListener());
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Order::class,
        ]);
    }
}

src/Controller/CartController.php
<?php

namespace App\Controller;

use App\Entity\OrderItem;
use App\Form\CartType;
use App\Manager\CartManager;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class CartController extends AbstractController
{
    /**
     * @Route("/cart", name="cart")
     */
    public function index(CartManager $cartManager, Request $request): Response
    {
        $cart = $cartManager->getCurrentCart();
        $form = $this->createForm(CartType::class, $cart);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $cart->setUpdatedAt(new \DateTime());
            $cartManager->add($cart);

            return $this->redirectToRoute('cart');
        }
        return $this->render('cart/index.html.twig', [
            'cart' => $cart,
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/cart/add", name="item_add")
     */
    public function addToDatabase(CartManager $cartManager)
    {
        $cart = $cartManager->getCurrentCart();
        $cartManager->save($cart);
        $cartManager->remove($cart);
        $this->addFlash("Success", "Check out successful");
        return $this->redirectToRoute('cart');
    }
//        /**
//         * @Route ("/cart/delete/{id}", name="item_delete")
//         */
//        public function deleteItem($id)
//        {
//            $item = $this->getDoctrine()->getRepository(OrderItem::class)->find($id);
//            $manager = $this->getDoctrine()->getManager();
//            $manager->remove($item);
//            $manager->flush();
//
//            $this->addFlash("Success", "Product has been deleted from cart");
//            return $this->redirectToRoute("cart");
//        }
}

templates/cart/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Cart{% endblock %}

{% block body %}
    {% for flash in app.flashes("Success") %}
        <p class="alert alert-primary"> {{ flash }} </p>
    {% endfor %}
    <div class="container mt-4">
        {% if cart.items.count > 0 %}
            <div class="row mt-4">
                <!-- List of items -->
                <div class="col-md-8">
                    {{ form_start(form) }}
                    <div class="card">
                        <div class="card-header bg-dark text-white d-flex">
                            <h5>Item</h5>
{#                            <div class="ms-auto">#}
{#                                {{ form_widget(form.clear, {'attr': {'class': 'btn btn-light'}}) }}#}
{#                            </div>#}
                        </div>
                        <ul class="list-group list-group-flush">
                            {% for item in form.items %}
                                <li class="list-group-item d-flex">
                                    <div class="flex-fill ms-2">
                                        <img src="{{ asset ('images/products/' ~ item.vars.data.product.image) }}"
                                             width="64">
                                    </div>
                                    <div class="flex-fill ms-2">
                                        <h5 class="mt-0 mb-0">{{ item.vars.data.product.name }}</h5>
                                        <small>{{ item.vars.data.product.description[:50] }}</small>
                                        <div class="form-inline mt-2">
                                            <div class="form-group mb-0 ms-2">
                                                {{ form_widget(item.quantity, {
                                                    'attr' : {
                                                        'class': 'form-control form-control-sm' ~ (item.quantity.vars.valid ? '' : 'is-invalid')
                                                    }
                                                }) }}
                                                <div class="invalid-feedback">
                                                    {{ form_errors(item.quantity) }}
                                                </div>
                                            </div>
                                            {{ form_widget(item.remove, {'attr': {'class': 'btn btn-dark btn-sm'}}) }}
{#                                            <a class="btn btn-dark btn-sm" href="{{ path ('item_delete', {'id': item.items.id}) }}">Delete</a>#}
                                        </div>
                                    </div>
                                    <div class="flex-fill text-right">
                                        <b>{{ item.vars.data.product.price }}$</b>
                                    </div>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                    {{ form_end(form, {'render_rest': false}) }}
                    <li class="list-group-item d-flex justify-content-between">
                            <div><b>Total: </b></div>
                            <span><b>{{ cart.total }} $</b></span>
                        <div class="ms-auto">
                            <a href="{{ path('item_add') }}" class="btn btn-warning">Checkout</a>
                        </div>
                    </li>
                </div>
            </div>
        {% else %}
            <div class="alert alert-info">
                Your cart is empty. Go to the <a href="{{ path('product_list') }}">product list</a>
            </div>
        {% endif %}
    </div>
{% endblock %}