src/Entity/Category.php
<?php

namespace App\Entity;

use App\Repository\CategoryRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CategoryRepository::class)
 */
class Category
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $Name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Description;

    /**
     * @ORM\OneToMany(targetEntity=Product::class, mappedBy="category")
     */
    private $products;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $date;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image;

    public function __construct()
    {
        $this->products = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(?string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    /**
     * @return Collection|Product[]
     */
    public function getProducts(): Collection
    {
        return $this->products;
    }

    public function addProduct(Product $product): self
    {
        if (!$this->products->contains($product)) {
            $this->products[] = $product;
            $product->setCategory($this);
        }

        return $this;
    }

    public function removeProduct(Product $product): self
    {
        if ($this->products->removeElement($product)) {
            // set the owning side to null (unless already changed)
            if ($product->getCategory() === $this) {
                $product->setCategory(null);
            }
        }

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(?\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getImage()
    {
        return $this->image;
    }

    public function setImage($image)
    {
        $this->image = $image;

        return $this;
    }
}

src/Controller/CategoryController.php
<?php

namespace App\Controller;

use App\Entity\Category;
use App\Form\CategoryFormType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use function PHPUnit\Framework\throwException;

class CategoryController extends AbstractController
{
    /**
     * @Route("/category", name="category_list")
     */
    public function viewAllCategory()
    {
        $categories = $this->getDoctrine()->getRepository(Category::class)->findAll();

        return $this->render('category/index.html.twig',
            [
                'categories' => $categories
            ]);
    }
    /**
     * @Route("/category/detail/{id}", name="category_detail")
     */
    public function viewDetailCategory($id)
    {
        $category = $this->getDoctrine()->getRepository(Category::class)->find($id);
        if ($category == null) {
            $this->addFlash("Error", "Category ID is invalid");
            return $this->redirectToRoute("category_list");
        }
        return $this->render('category/detail.html.twig',
            [
                'category' => $category
            ]);
    }

    /**
     * @Route("/category/delete/{id}", name="category_delete")
     */
    public function deleteCategory($id)
    {
        $category = $this->getDoctrine()->getRepository(Category::class)->find($id);
        if ($category == null) {
            $this->addFlash("Error", "Category ID is invalid");
            return $this->redirectToRoute("category_list");
        }
        $manager = $this->getDoctrine()->getManager();
        $manager->remove($category);
        $manager->flush();

        $this->addFlash("Success", "Category has been deleted");
        return $this->redirectToRoute("category_list");
    }
    /**
     * @Route("/category/create", name="category_create")
     */
    public function createCategory(Request $request)
    {
        $category = new Category();
        $form = $this->createForm(CategoryFormType::class, $category);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            //get image from upload file
            $image = $category->getImage();

            //create unique image name
            $fileName = md5(uniqid());
            $fileExtension = $image->guessExtension();
            $imageName = $fileName . '.' . $fileExtension;

            //move uploaded image to defined location
            try {
                $image->move(
                    $this->getParameter('category_image'), $imageName
                );
            } catch (FileException $e) {
                throwException($e);
            }

            //set imageName to database
            $category->setImage($imageName);

            $manager = $this->getDoctrine()
                ->getManager();
            $manager->persist($category);
            $manager->flush();
            $this->addFlash("Success", "Add category successfully !");
            return $this->redirectToRoute("category_list");
        }

        return $this->render("category/create.html.twig",
            [
                'form'=>$form->createView()
            ]);
    }

    /**
     * @Route("/category/update/{id}", name="category_update")
     */
    public function updateCategory(Request $request, $id)
    {
        $category = $this->getDoctrine()->getRepository(Category::class)->find($id);
        $form = $this->createForm(CategoryFormType::class, $category);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $uploadedFile = $form['image']->getData();
            if ($uploadedFile != null) {
                $image = $category->getImage();

                //create unique image name
                $fileName = md5(uniqid());
                $fileExtension = $image->guessExtension();
                $imageName = $fileName . '.' . $fileExtension;

                //move uploaded image to defined location
                try {
                    $image->move(
                        $this->getParameter('category_image'), $imageName
                    );
                } catch (FileException $e) {
                    throwException($e);
                }

                //set imageName to database
                $category->setImage($imageName);
            }
            //get image from upload file


            $manager = $this->getDoctrine()
                ->getManager();
            $manager->persist($category);
            $manager->flush();
            $this->addFlash("Success", "Update category successfully !");
            return $this->redirectToRoute("category_detail", ['id' => $id]);
        }

        return $this->render("category/update.html.twig",
            [
                'form'=>$form->createView()
            ]);
    }
}

templates/category/create.html.twig
{% extends "base.html.twig" %}

{% block title %} Create product {% endblock %}

{% block body %}
    <div class="container-fluid mt-3">
        <h2 class="text-center mt-5">CREATE CATEGORY</h2>
            <div class="col-md-6"></div>
            {{ form_start (form, {'attr': {'class': 'm-3'}}) }}
            <div class="form-group">
                {{ form_label (form.Name) }}
                {{ form_widget (form.Name, {'attr': {'class' : 'form-control'}}) }}
            </div>
            <div class="form-group">
                {{ form_label (form.Description) }}
                {{ form_widget (form.Description, {'attr': {'class' : 'form-control'}}) }}
            </div>
            <div class="form-group">
                {{ form_label (form.date) }}
                {{ form_widget (form.date, {'attr': {'class' : 'form-control'}}) }}
            </div>
            <div class="form-group">
                {{ form_label (form.image) }}
                {{ form_widget (form.image, {'attr': {'class' : 'form-control'}}) }}
            </div>

            <div class="form-group text-center mt-3">
                <button class="btn btn-primary btn-lg">CREATE</button>
            </div>
            {{ form_end (form) }}
    </div>
{% endblock %}

templates/category/detail.html.twig
{% extends 'base.html.twig' %}

{% block title %} Category Detail {% endblock %}

{% block body %}

    <div class="container-fluid">
        <a class="btn btn-primary" href="{{ path ('category_list') }}">Category List</a>
        <table class="table table-striped">
            <thead>
            <tr>
                <th scope="col">Category Name</th>
                <th scope="col">Category Description</th>
                <th scope="col">Category Date</th>
                <th scope="col">Category Image</th>
                <th scope="col">Category Products</th>
                <th scope="col">Actions</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td scope="row">{{ category.name }}</td>
                <td scope="row">{{ category.description }}</td>
                <td scope="row">{{ category.date  | date("Y-m-d") }}</td>
                <td scope="row">
                    {% if category.image != null %}
                        <img src="{{ asset ('images/categories/' ~ category.image) }}" width="80px"
                             height="80px">
                    {% else %}
                        <img src="{{ asset ('images/categories/category.png') }}" width="60px"
                             height="60px">
                    {% endif %}
                </td>
                <td scope="row">
                    {% for a in category.products %}
                        {% if a is not null %}
                            <a href="{{ path('product_detail', {'id' : a.id }) }}">
                                {{ a.name }}
                            </a>
                        {% else %}
                            N/A
                        {% endif %}
                        <br>
                    {% endfor %}
                </td>

                {# ManyToOne relationship #}
                {# <td scope="row"> #}
                {# <a href="{{ path('author_detail', {'id' : category.author.id }) }}"> #}
                {# {{ category.author.name }} #}
                {# </a> #}
                {# <br> #}
                {# </td> #}

                <td scope="row">
                    <a class="btn btn-warning"
                       href="{{ path ( 'category_update' , {'id' : category.id } ) }}">Update</a>
                    <a class="btn btn-danger" href="{{ path ( 'category_delete' , {'id' : category.id } ) }}"
                       onclick="return confirm('Are you sure to delete ?')"
                    >Delete</a>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
{% endblock %}

templates/category/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Category List{% endblock %}

{% block body %}

    <div class="container">
        {% for flash in app.flashes("Success") %}
            <p class="alert alert-success"> {{ flash }} </p>
        {% endfor %}
        {% for flash in app.flashes("Error") %}
            <p class="alert alert-danger"> {{ flash }} </p>
        {% endfor %}
    </div>

    <div class="container m-3">
        <a class="btn btn-primary" href="{{ path ('category_create') }}">Create Category</a>
        <br>
        <br>
        <table class="table table-striped">
            <tr>
                <th class="col">Category ID</th>
                <th class="col">Category Name</th>
                <th class="col">Actions</th>
            </tr>
            {% for category in categories %}
                <tr>
                    <td class="col">{{ category.id }}</td>
                    <td class="col">{{ category.name }}</td>
                    <td class="col">
                        <a class="btn btn-info" href="{{ path ('category_detail', {'id': category.id}) }}">Detail</a>
                        <a class="btn btn-warning"
                           href="{{ path ( 'category_update' , {'id' : category.id } ) }}">Update</a>
                        <a class="btn btn-danger" href="{{ path ( 'category_delete' , {'id' : category.id } ) }}"
                           onclick="return confirm('Are you sure to delete ?')"
                        >Delete</a>
                    </td>
                </tr>
            {% endfor %}
        </table>
    </div>
{% endblock %}

templates/category/update.html.twig
{% extends "base.html.twig" %}

{% block title %} Update Category {% endblock %}

{% block body %}
    <div class="container-fluid mt-3">
        <h2 class="text-center mt-5">UPDATE CATEGORY</h2>
        <div class="col-md-6"></div>
        {{ form_start (form, {'attr': {'class': 'm-3'}}) }}
        <div class="form-group">
            {{ form_label (form.Name) }}
            {{ form_widget (form.Name, {'attr': {'class' : 'form-control'}}) }}
        </div>
        <div class="form-group">
            {{ form_label (form.Description) }}
            {{ form_widget (form.Description, {'attr': {'class' : 'form-control'}}) }}
        </div>
        <div class="form-group">
            {{ form_label (form.date) }}
            {{ form_widget (form.date, {'attr': {'class' : 'form-control'}}) }}
        </div>
        <div class="form-group">
            {{ form_label (form.image) }}
            {{ form_widget (form.image, {'attr': {'class' : 'form-control'}}) }}
        </div>
        <div class="form-group text-center mt-3">
            <button class="btn btn-primary btn-lg">UPDATE</button>
        </div>
        {{ form_end (form) }}
    </div>
{% endblock %}